:- module start.
:- interface.
:- import_module io.
:- pred main(io::di, io::uo) is det.

% Do not edit this file. Implement mset.m until all tests pass.

:- implementation.
:- import_module mset.
:- import_module bool.
:- import_module int.
:- import_module list.
:- import_module string.

:- pred check(string::in, bool::in, io::di, io::uo) is det.
check(Name, yes, !IO) :- io.format("PASS: %s\n", [s(Name)], !IO).
check(Name, no,  !IO) :- io.format("FAIL: %s\n", [s(Name)], !IO).

main(!IO) :-
    % Build a multiset: {1, 1, 2}
    mset.empty(M0),
    mset.insert(1, M0, M1),
    mset.insert(2, M1, M2),
    mset.insert(1, M2, M3),

    % Count
    mset.count(1, M3, C1),
    check("count(1) = 2",   ( C1 = 2 -> yes ; no ), !IO),
    mset.count(2, M3, C2),
    check("count(2) = 1",   ( C2 = 1 -> yes ; no ), !IO),
    mset.count(9, M3, C9),
    check("count(9) = 0",   ( C9 = 0 -> yes ; no ), !IO),

    % Size
    check("size = 3",       ( mset.size(M3) = 3 -> yes ; no ), !IO),

    % Remove one occurrence of 1 → {1, 2}
    ( mset.remove(1, M3, M4) ->
        mset.count(1, M4, C1b),
        check("after remove(1): count(1) = 1", ( C1b = 1 -> yes ; no ), !IO),
        check("after remove(1): size = 2",     ( mset.size(M4) = 2 -> yes ; no ), !IO)
    ;
        check("remove(1) succeeded", no, !IO)
    ),

    % Remove absent element fails
    check("remove(9) fails", ( mset.remove(9, M3, _) -> no ; yes ), !IO),

    % to_list length matches size
    Lst = mset.to_list(M3),
    check("to_list length = size",
        ( list.length(Lst) = mset.size(M3) -> yes ; no ), !IO).
